### ISSUE TITLE
@nestjs-rentars - refactor car entity

### ISSUE THREAD

**Issue by Yokoso** [Yokoso/rentars#20]
#### Description
Car entity does not contain specific information about the car like make, model, etc, but only a simple name. Refactor should simplify the implementation of the filter engine. Research on which fields to include.

#### Files
A list of relevant files for this issue.
- nestjs-rentars\src\components\cars\dto\new-car.input.ts
- nestjs-rentars\src\components\cars\entities\car.ts

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1. Research other car rental websites for information
- [ ] Task 2. Reseed of the database may be needed.
- [ ] Task 3. Refactor Car class in car.ts
- [ ] Task 4. Refactor NewCarInput class in new-car.input.ts
